name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
       description: image tag
       required: true
       default: latest
env:
  tag: zhuyunjie0207/demo_web_api:${{ github.event.inputs.tag }}
jobs:
   pull_request:
      runs-on: ubuntu-latest
      needs: build_and_push
      steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with: 
          repository: Albertzue/exampleAPI_manifests  
          path: manifests
          sparse-checkout: |
            values.yaml
          sparse-checkout-cone-mode: false
      - name: update_image
        shell: bash
        run: |  
              cd manifests
              ls
              sed 's/\:*$/\:${{ github.event.inputs.tag }}/2' 
              cat values.yaml
   build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: GetInfo
      shell: bash
      run: |  
            ls -a
            pwd
    - name: Build and push
      uses: docker/build-push-action@v4.1.1
      with:
         context: .
         file: ./exampleAPI/Dockerfile
         push: true
         tags:  ${{ env.tag }}
         
   
  
