name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
       description: image tag
       required: true
       default: latest
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: GetInfo
      shell: bash
      run: |  
            ls -a
            pwd
    - name: Build and push
      uses: docker/build-push-action@v4.1.1
      with:
         context: .
         file: ./exampleAPI/Dockerfile
         push: true
         tags: zhuyunjie0207/demo_web_api:latest
