name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4.1.1
      with:
         context: .
         file: ./exampleAPI/Dockerfile
         push: true
         tags: zhuyunjie0207/demo_web_api:$(date +%s)
