name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: GetInfo
      shell: bash
      run: |  
            ls -a
            pwd
    - name: Build and push
      uses: docker/build-push-action@v4.1.1
      with:
         context: /home/runner/work/exampleAPI/exampleAPI
         file: Dockerfile
         push: true
         tags: zhuyunjie0207/demo_web_api:latest
